org: jaganoerworks
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  httpApi:
    authorizers:
      auth0Authorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://dev-hzy2ijocvhfmctf6.jp.auth0.com/
        audience:
          - https://myapi.com
          - https://mysecondapi.com

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /hello
          method: get
          authorizer:
            name: auth0Authorizer
