org: jaganoerworks
app: aws-node-project
service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: post
          cors:
            origin: "https://www.example.com" # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true # <-- Specify whether credentials are allowed
