org: jaganoerworks
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  httpApi:
    cors: true
    authorizers:
      auth0Authorizer:
        identitySource: $request.header.Authorization
        issuerUrl: ${env:AUTH0_DOMAIN}
        audience:
          - ${env:AUTH0_AUDIENCE}

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /hello
          method: get
          authorizer:
            name: auth0Authorizer
